version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - jenkins_data:/var/jenkins_home
    networks:
      - my_network

  dependency-track:
    image: dependencytrack/bundled:latest
    container_name: dependency-track
    ports:
      - '8081:8080'
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  jenkins_data:
